// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azlstgtcvbpxcckevxxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6bHN0Z3RjdmJweGNja2V2eHh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjkyOTAsImV4cCI6MjA2MDkwNTI5MH0.RL7x2SFF7Fk4U3b_M8uf5m1WTtgt-g8rEwClnUjfch4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);